# DB config : skal pege til ../whoknows.db
# Database connection settings

# Kan udkommenteres når db skal bruges
#development:
  #adapter: sqlite3
  #database: ../whoknows.db

# For local development and Docker-dev
development:
  adapter: sqlite3
  database: <%= ENV.fetch('DATABASE_PATH', '../whoknows.db') %>
  pool: 5
  timeout: 5000

# For production (Docker)
production:
  adapter: sqlite3
  database: <%= ENV.fetch('DATABASE_PATH', '../whoknows.db') %>
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000