# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '~> 7.0'
gem 'bcrypt', '~> 3.1'
gem 'dotenv'
gem 'digest' # To hash IP addresses for logging unique users
# ostruct is no longer part of default gems from Ruby 4.0
# so we include it explicitly to avoid warnings
gem 'ostruct'
gem 'pg', '~> 1.5' # PostgreSQL adapter for production and development
gem 'puma'
gem 'rackup'
gem 'rake' # Runs the db:migrate command
gem 'sinatra', '~> 4.0'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.6', group: :test # Only needed for in-memory test database

group :test do
  gem 'committee' # For testing API responses against OpenAPI specs
  gem 'rack-test' # Simulates HTTP requests in tests
  gem 'rspec'
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'brakeman', require: false
  gem 'guard' # Watches for file changes
  gem 'guard-shell' # Allows Guard to run shell-kommands (to restart the server when files change)
  gem 'rubocop', '~> 1.60', require: false # When app is running, don't load RuboCop. We load it through CLI
end
